"""
backend/app/engines/packet_intelligence/zeek/reader.py
------------------------------------------------------
Zeek Reader Engine (Phase 4).

Reads Zeek JSON logs incrementally and yields structured raw records.
Acts as a parsing boundary, preserving source Zeek data without
canonical coercion.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterator

from .errors import ZeekRunnerError, ZeekRunnerErrorCode
from .result import ZeekRunnerResult


@dataclass(frozen=True)
class RawZeekRecord:
    """A successfully parsed Zeek JSON log record."""

    acquisition_id: str
    source_log: str
    log_type: str
    record: dict[str, Any]
    line_number: int


@dataclass(frozen=True)
class RawZeekErrorRecord:
    """A parsing error encountered during Zeek log reading."""

    acquisition_id: str
    source_log: str
    line_number: int
    error_type: str
    raw_line: str


class ZeekReader:
    """Reads Zeek JSON logs generated by the ZeekRunner."""

    def __init__(self) -> None:
        pass

    def read(
        self, result: ZeekRunnerResult
    ) -> Iterator[RawZeekRecord | RawZeekErrorRecord]:
        """Read all generated Zeek logs and yield records incrementally.

        Parameters:
            result: The execution result from the ZeekRunner.

        Yields:
            RawZeekRecord for valid JSON lines.
            RawZeekErrorRecord for malformed lines.

        Raises:
            ZeekRunnerError: If the output directory is inaccessible.
        """
        output_dir = result.output_directory
        if not output_dir.exists() or not output_dir.is_dir():
            raise ZeekRunnerError(
                ZeekRunnerErrorCode.OUTPUT_DIR_ERROR,
                f"Output directory does not exist or is not a directory: {output_dir}",
            )

        for log_name in result.generated_logs:
            log_path = output_dir / log_name
            if not log_path.exists() or not log_path.is_file():
                # Missing logs are not treated as failures.
                continue

            # Extract log type (e.g. 'conn.log' -> 'conn')
            log_type = log_path.stem if log_path.suffix == ".log" else log_name
            if log_name.endswith(".log"):
                log_type = log_name[:-4]
            else:
                log_type = log_name

            yield from self._read_log_file(
                log_path=log_path,
                acquisition_id=result.acquisition_id,
                log_type=log_type,
            )

    def _read_log_file(
        self, log_path: Path, acquisition_id: str, log_type: str
    ) -> Iterator[RawZeekRecord | RawZeekErrorRecord]:
        """Read a single Zeek JSON log file incrementally."""
        try:
            with open(log_path, "r", encoding="utf-8") as f:
                for line_idx, line in enumerate(f):
                    line_number = line_idx + 1
                    line = line.strip()

                    if not line:
                        continue
                    if line.startswith("#"):
                        # Skip TSV metadata headers if Zeek mistakenly includes them
                        continue

                    try:
                        parsed = json.loads(line)
                        if not isinstance(parsed, dict):
                             # JSON parsed to a scalar or list, which isn't a valid Zeek record
                             yield RawZeekErrorRecord(
                                acquisition_id=acquisition_id,
                                source_log=log_path.name,
                                line_number=line_number,
                                error_type="INVALID_RECORD_TYPE",
                                raw_line=line[:200],  # Truncate for safety
                            )
                             continue

                        yield RawZeekRecord(
                            acquisition_id=acquisition_id,
                            source_log=log_path.name,
                            log_type=log_type,
                            record=parsed,
                            line_number=line_number,
                        )
                    except json.JSONDecodeError as exc:
                        yield RawZeekErrorRecord(
                            acquisition_id=acquisition_id,
                            source_log=log_path.name,
                            line_number=line_number,
                            error_type="JSON_DECODE_ERROR",
                            raw_line=line[:200],  # Truncate for safety
                        )
        except OSError as exc:
            yield RawZeekErrorRecord(
                acquisition_id=acquisition_id,
                source_log=log_path.name,
                line_number=0,
                error_type="OS_ERROR",
                raw_line=str(exc)[:200],
            )
