import { FileText, X, Shield, Clock, Hash, Database } from 'lucide-react';
import type { ReportResponse } from '../types';

interface ReportDetailModalProps {
  report: ReportResponse | null;
  onClose: () => void;
}

export function ReportDetailModal({ report, onClose }: ReportDetailModalProps) {
  if (!report) return null;

  return (
    <>
      <div className="fixed inset-0 bg-black/50 z-40 backdrop-blur-sm" onClick={onClose} aria-hidden="true" />
      <div
        className="fixed left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 w-full max-w-lg bg-surface border border-border-subtle rounded-lg p-6 z-50 shadow-2xl space-y-5"
        role="dialog"
        aria-modal="true"
        aria-label="Report Detail"
      >
        {/* Header */}
        <div className="flex items-center justify-between pb-3 border-b border-border-subtle">
          <div className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-accent" aria-hidden="true" />
            <h2 className="text-base font-semibold text-primary">
              {report.title || `Report v${report.version}`}
            </h2>
          </div>
          <button
            onClick={onClose}
            className="rounded p-1 hover:bg-surface-elevated text-muted hover:text-primary transition-colors"
            aria-label="Close report detail"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Metadata section */}
        <div className="space-y-2.5 bg-surface-elevated/40 p-4 rounded border border-border-subtle text-xs">
          <div className="flex justify-between">
            <span className="text-muted flex items-center gap-1">
              <FileText className="h-3.5 w-3.5" /> Type:
            </span>
            <span className="text-primary font-medium uppercase font-mono">{report.report_type}</span>
          </div>
          <div className="flex justify-between">
            <span className="text-muted flex items-center gap-1">
              <Clock className="h-3.5 w-3.5" /> Format & Version:
            </span>
            <span className="text-primary font-mono">{report.format.toUpperCase()} (v{report.version})</span>
          </div>
          <div className="flex justify-between">
            <span className="text-muted flex items-center gap-1">
              <Clock className="h-3.5 w-3.5" /> Generated:
            </span>
            <span className="text-secondary font-mono">{new Date(report.generated_at).toLocaleString()}</span>
          </div>
          {report.generated_by && (
            <div className="flex justify-between">
              <span className="text-muted">Generated By:</span>
              <span className="text-secondary font-mono">{report.generated_by}</span>
            </div>
          )}
          <div className="flex justify-between pt-1 border-t border-border-subtle">
            <span className="text-muted flex items-center gap-1">
              <Hash className="h-3.5 w-3.5" /> SHA-256 Digest:
            </span>
            <span className="text-primary font-mono truncate max-w-[200px]" title={report.sha256}>
              {report.sha256}
            </span>
          </div>
          <div className="flex justify-between">
            <span className="text-muted flex items-center gap-1">
              <Database className="h-3.5 w-3.5" /> Storage Reference:
            </span>
            <span className="text-muted font-mono">{report.minio_bucket} / {report.object_key}</span>
          </div>
        </div>

        <div className="flex items-center gap-2 p-2.5 rounded bg-surface-elevated border border-border-subtle text-[11px] text-muted">
          <Shield className="h-3.5 w-3.5 text-accent flex-shrink-0" />
          <span>Report artifact integrity verified with SHA-256 digest.</span>
        </div>

        <div className="flex justify-end pt-2 border-t border-border-subtle">
          <button
            onClick={onClose}
            className="px-3.5 py-1.5 text-xs text-secondary hover:text-primary border border-border-subtle rounded hover:bg-surface-elevated transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </>
  );
}
